### ISSUE TITLE
Cannot sign a parcel

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain-helicopter#18]
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.decrypt (/home/sgkim126/workspace/kodebox/app/helicopter/node_modules/codechain-keystore/lib/logic/crypto.js:53:21)
    at Object.<anonymous> (/home/sgkim126/workspace/kodebox/app/helicopter/node_modules/codechain-keystore/lib/model/keys.js:165:43)
    at step (/home/sgkim126/workspace/kodebox/app/helicopter/node_modules/codechain-keystore/lib/model/keys.js:32:23)
    at Object.next (/home/sgkim126/workspace/kodebox/app/helicopter/node_modules/codechain-keystore/lib/model/keys.js:13:53)
    at fulfilled (/home/sgkim126/workspace/kodebox/app/helicopter/node_modules/codechain-keystore/lib/model/keys.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
The exception is thrown on [line 79](https://github.com/CodeChain-io/codechain-helicopter/blob/master/index.ts#L79).
@GNUp any hint?
The error is thrown when on the commit be4288eda5d5290f95a47bd255c65e81fd262e3b too.

**Comment by majecty** [comment]
@sgkim126 
Cause of this error is the mismatch of KeyStore version.
You can resolve this by updating codechain-sdk-js.
