### ISSUE TITLE
Exception handling when server connection fails

### ISSUE THREAD

**Issue by posgnu** [CodeChain-io/codechain-helicopter#5]
When getting account's information from the server is failed, helicopter exit with
```
(node:15620) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token F in JSON at position 0
    at JSON.parse (<anonymous>)
    at ClientBrowser._parseResponse (/home/ubuntu/codechain-helicopter/node_modules/jayson/lib/client/browser.js:121:21)
    at /home/ubuntu/codechain-helicopter/node_modules/jayson/lib/client/browser.js:96:10
    at node_fetch_1.default.then.then.text (/home/ubuntu/codechain-helicopter/node_modules/codechain-sdk/lib/rpc/index.js:43:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
This kind of situation should be handled.

**Comment by posgnu** [comment]
```
(node:24388) UnhandledPromiseRejectionWarning: StatusCodeError: 502 - "ECONNREFUSED"
    at new StatusCodeError (/home/ubuntu/codechain-helicopter/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/ubuntu/codechain-helicopter/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/ubuntu/codechain-helicopter/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/ubuntu/codechain-helicopter/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/ubuntu/codechain-helicopter/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/ubuntu/codechain-helicopter/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:24388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by GNUp** [comment]
After moving the `request` into try box, first error removed and second error newly appeared.

**Comment by posgnu** [comment]
The problem was solved after putting a request in a try box.
